name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below so we can reproduce and fix it.

  - type: input
    id: version
    attributes:
      label: SafeClaw version
      description: Run `npx safeclaw --version` or check the Settings page
      placeholder: "0.1.6"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: Describe what you observed...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug
      placeholder: |
        1. Run `npx safeclaw start`
        2. Navigate to Interception page
        3. Click "Add Pattern"
        4. ...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      options:
        - Dashboard
        - Command Interception
        - Session Monitoring
        - Threat Detection
        - Access Control
        - CLI (start/reset/status/doctor/config/logs)
        - OpenClaw Connection
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, browser, etc.
      placeholder: |
        - OS: macOS 15.2
        - Node: 22.0.0
        - Browser: Chrome 130
        - OpenClaw version (if relevant): ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / errors
      description: Any relevant console output, browser errors, or logs from `~/.safeclaw/logs/debug.log`
      render: shell
    validations:
      required: false
