name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make SafeClaw better? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve, or what use case does it enable?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Dashboard
        - Command Interception
        - Session Monitoring
        - Threat Detection
        - Access Control
        - CLI
        - OpenClaw Integration
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links, or anything else that helps explain
    validations:
      required: false
